DECLARE @FEATURE_ID INT = 1333034,  @CountyFeatureID INT = 1605081, @StateFeatureID INT = 1779807

/*
1333034
2346446
1936066
331646
1686342
1686135
322726
*/

SELECT * FROM Appdata.FeatureSearchName WHERE FeatureID=1333034;
--SELECT* FROM   USGS.AllName where FEATURE_NAME_OFFICIAL=''

--SELECT* FROM [USGS].[NationalFile] WHERE FEATURE_ID = @FEATURE_ID;
SELECT* FROM   USGS.AllName WHERE FEATURE_ID = @FEATURE_ID
--SELECT* FROM   USGS.Concise WHERE FEATURE_ID = @FEATURE_ID
--SELECT* FROM USGS.HistoricalFeature WHERE FEATURE_ID = @FEATURE_ID;

--SELECT* FROM USGS.GovernmentUnit  WHERE FEATURE_ID = @CountyFeatureID  and UNIT_TYPE='County';
--SELECT* FROM USGS.GovernmentUnit  WHERE FEATURE_ID = @StateFeatureID  and UNIT_TYPE='State';


--SELECT* FROM  USGS.NationalFederalCode  WHERE FEATURE_ID = @FEATURE_ID;
--
--SELECT* FROM  USGS.FeatureDescriptionHistory WHERE FEATURE_ID = @FEATURE_ID;
--SELECT* FROM USGS.GovernmentUnit  WHERE FEATURE_ID = @FEATURE_ID;
--SELECT* FROM   USGS.PopulatedPlace WHERE FEATURE_ID = @FEATURE_ID;
--





